sudo: required
#tell travis that this service is needed
language: java
jdk: oraclejdk11
service:
    - docker
before_install:
    - chmod +x mvnw
script:
#prepare dockerfile for build and tag using docker id
    - mvn package -DskipTests
    - docker build -t ashirvaddesai/petapplication -f Dockerfile.dev .
    - docker run -e CI=true ashirvaddesai/petapplication
deploy:
    provider: elasticbeanstalk
    region: 'ap-south-1'
    app: 'ShareACare'
    env: 'Shareacare-env-1'
    bucket_name: 'elasticbeanstalk-ap-south-1-924847644856'
    bucket_path: 'ShareACare'
    on:
        branch: master
# aws acess key and and id stored in travis project->settings->env
#shareacare-env-1.eba-fzndm6ku.ap-south-1.elasticbeanstalk
    access_key_id: $aws_access_key
    secret_access_key: $aws_secret_key
