sudo: required
#tell travis that this service is needed
language: java
jdk: oraclejdk11
service:
    - docker
#prepare dockerfile for build and tag using docker id
#ashirvaddesai/PetApplication can be replaced by any tag
#before_install:
before_install:
    - chmod +x mvnw
script:
    - mvn package -DskipTests
    - docker build -t ashirvaddesai/petapplication -f Dockerfile.dev .
    - docker run -e CI=true ashirvaddesai/
#http://shareacare-env-1.eba-fzndm6ku.ap-south-1.elasticbeanstalk.com/
deploy:
    provider:elasticbeanstalk
    region:"ap-south-1"
    app: "ShareACare"
    env: "Shareacare-env-1"
    bucket_name: "elasticbeanstalk-ap-south-1-924847644856"
    bucket_path: "ShareACare" #same as app name
    on:
        branch:master
    access_key_id:$aws_access_key #stored in travis project->settings->env
    secret_access_key:
        secure:"$aws_secret_key"