sudo: required
#tell travis that this service is needed
language: java
jdk: oraclejdk11
service:
    - docker
#prepare dockerfile for build and tag using docker id
#ashirvaddesai/PetApplication can be replaced by any tag
#before_install:
before_install:
    - chmod +x mvnw
script:
    - mvn package -DskipTests
    - docker build -t ashirvaddesai/petapplication -f Dockerfile.dev .
    - docker run -e CI=true ashirvaddesai/petapplication